# Prometheus 配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'go-dev-cluster'
    environment: 'development'

# 规则文件配置
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 数据抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s
    metrics_path: /metrics

  # Go 应用监控 (需要应用暴露 metrics 端点)
  - job_name: 'go-application'
    static_configs:
      - targets: ['go-dev:8087']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Redis 监控 (需要 redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # MySQL 监控 (需要 mysqld_exporter) 
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx 监控 (需要 nginx_exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /metrics

  # Elasticsearch 监控
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 30s
    metrics_path: /_prometheus/metrics

  # Kafka 监控 (通过 JMX)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9997']
    scrape_interval: 30s

  # 节点监控 (需要 node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

# 告警管理器配置 (可选)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - "alertmanager:9093"

# 远程写入配置 (可选)
# remote_write:
#   - url: "http://remote-storage:8086/api/v1/prom/write"

# 远程读取配置 (可选)  
# remote_read:
#   - url: "http://remote-storage:8086/api/v1/prom/read"
