version: '3.8'

services:
  go-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-dev-env
    hostname: go-dev
    ports:
      - "2222:22"  # SSH 端口映射
      - "8087:8087"  # 应用端口
      - "8081:8081"  # 调试端口
      - "9000:9000"  # 其他服务端口
    volumes:
      # 挂载当前目录到容器的 /workspace
      - .:/workspace
      # 挂载 Go 模块缓存
      - go-mod-cache:/go/pkg/mod
      # 挂载 Go 构建缓存
      - go-build-cache:/root/.cache/go-build
    environment:
      - GOPATH=/go
      - GOROOT=/usr/local/go
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - go-dev-network

volumes:
  go-mod-cache:
  go-build-cache:

networks:
  go-dev-network:
    driver: bridge
